name: CI

on:
  push:
    branches: [ main, feature/cursor-drag ]
  pull_request:
    branches: [ main ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build debug
      run: ./gradlew assembleDebug
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/

  lint-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run lint
      run: ./gradlew lint
    - name: Run unit tests
      run: ./gradlew test
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: app/build/reports/tests/

  build-release:
    runs-on: ubuntu-latest
    needs: [lint-unit]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build release
      run: ./gradlew assembleRelease
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/ 